[SERVICE]
    Flush         1
    Daemon        Off
    Log_Level     info
    Parsers_File  /fluent-bit/etc/parsers.conf
    HTTP_Server   On
    HTTP_Listen   0.0.0.0
    HTTP_Port     2020

[INPUT]
    Name              tail
    Path              /var/lib/docker/containers/*/*.log
    Parser            docker
    Tag               bancassurance.docker.*
    Path_Key          source_path
    DB                /tmp/flb_docker.db
    Mem_Buf_Limit     50MB
    Skip_Long_Lines   On
    Refresh_Interval  5
    Read_from_Head    True

[FILTER]
    Name       parser
    Match      bancassurance.docker.*
    Key_Name   source_path
    Parser     docker_path
    Reserve_Data On

[FILTER]
    Name    modify
    Match   bancassurance.docker.*
    Rename  container_id container_name

[FILTER]
    Name    record_modifier
    Match   bancassurance.docker.*
    Record  host ${HOSTNAME}
    Record  platform bancassurance
    Record  environment dev

[OUTPUT]
    Name                es
    Match               bancassurance.docker.*
    Host                elasticsearch
    Port                9200
    Logstash_Format     On
    Logstash_Prefix     bancassurance-logs
    Replace_Dots        On
    Suppress_Type_Name  On
    Retry_Limit         False
